package net.sf.jclec.binarray.mut;

import net.sf.jclec.binarray.BinArrayIndividual;
import net.sf.jclec.binarray.BinArrayMutator;

/**
 * One locus mutation in BinArrayIndividuals
 * 
 * @author Sebastian Ventura
 */

public class OneLocusMutator extends BinArrayMutator
{
	/////////////////////////////////////////////////////////////////
	// --------------------------------------- Serialization constant
	/////////////////////////////////////////////////////////////////
	
	/** Generated by Eclipse */
	
	private static final long serialVersionUID = 4051327838076744754L;

	/////////////////////////////////////////////////////////////////
	// ------------------------------------------------- Constructors
	/////////////////////////////////////////////////////////////////
	
	/**
	 * Empty constructor
	 */
	
	public OneLocusMutator() 
	{
		super();
	}

	/////////////////////////////////////////////////////////////////
	// ----------------------------------------------- Public methods
	/////////////////////////////////////////////////////////////////

	// AbstractMutator methods

	/**
	 * {@inheritDoc}
	 */
	
	@Override
	protected void mutateNext() 
	{
		// Genome length
		int gl = species.getGenotypeLength();
		// Individual to be mutated
		BinArrayIndividual mutant = 
			(BinArrayIndividual) parentsBuffer.get(parentsCounter);
		// Creates mutant genotype
		byte [] mgenome = new byte[gl];
		System.arraycopy(mutant.getGenotype(), 0, mgenome, 0, gl);
		// Choose mutation point
		int mp = getMutableLocus();
		// Flip selected point
		flip(mgenome, mp);
		// Returns mutant
		sonsBuffer.add(species.createIndividual(mgenome));
	}

/*
 * El mtodo realiza las siguientes acciones:
 * 
 * 1) Crea el genotipo del individuo, copiando el del padre
 * 2) Elige un punto de mutacin al azar, invocando al mtodo 
 *    getMutableLocus()
 * 3) Muta el locus elegido, invocando a flip(int)
 */
	
	// java.lang.Object methods

	public boolean equals(Object other)
	{
		if (other instanceof OneLocusMutator) {
			return true;
		}
		else {
			return false;
		}
	}
}

