package net.sf.jclec.realarray.rec;


/**
 * Hamacher Connectives
 * 
 * @author Alberto Lamarca-Rosales 
 * @author Sebastian Ventura
 */

public class HamacherConnectives extends AbstractFuzzyConnectives 
{
	/////////////////////////////////////////////////////////////////
	// --------------------------------------- Serialization constant
	/////////////////////////////////////////////////////////////////
	
	/** Generated by eclipse */
	
	private static final long serialVersionUID = 4417091839350797670L;

	/////////////////////////////////////////////////////////////////
	// ------------------------------------------------- Constructors
	/////////////////////////////////////////////////////////////////
	
	/**
	 * Empty constructor
	 */
	
	public HamacherConnectives() 
	{
		super();
	}

	/////////////////////////////////////////////////////////////////
	// ---------------------------------- AbstractConnectives methods
	/////////////////////////////////////////////////////////////////

	/**
	 * Hamacher Function m
	 */
	public double m(double x, double y) 
	{
		if(x==0 || y==0)
			return 0.0;
		else
			return ( 1/(((y-(y*alpha)-(x*y)+(x*alpha))/(x*y))+1) );
	}

	/**
	 * Hamacher Function s
	 */
	public double s(double x, double y) 
	{
		if(x==y && x==1)
			return 1;
		else
			return (x+y-2*x*y)/(1-x*y);
	}

	/**
	 * Hamacher Function f
	 */
	public double f(double x, double y) 
	{
		if(x==0 && y==0)
			return 0;
		else
			return (x*y)/(x+y-(x*y));
	}

	/**
	 * Hamacher Function l
	 */
	public double l(double x, double y) 
	{
		return m(f(x,y),s(x,y));
	}
}
