package net.sf.jclec.util.random;

/**
 * Mersenne Twister Factory
 * 
 * @author Sebastian Ventura
 */

public class RanmtFactory extends AbstractRandGenFactory 
{
	/////////////////////////////////////////////////////////////////
	// --------------------------------------- Serialization constant
	/////////////////////////////////////////////////////////////////
	
	/** Generated by Eclipse */
	
	private static final long serialVersionUID = -1837496618859662406L;

	/////////////////////////////////////////////////////////////////
	// ------------------------------------------------- Constructors
	/////////////////////////////////////////////////////////////////
	
	/**
	 * Empty constructor.
	 */
	
	public RanmtFactory() 
	{
		super();
	}

	/////////////////////////////////////////////////////////////////
	// ------------------------- Implementing IRandGenFactory methods 
	/////////////////////////////////////////////////////////////////
	
	/**
	 * {@inheritDoc}
	 */

	public IRandGen createRandGen() 
	{
		return new Ranmt(seedGenerator.nextSeed());
	}
}
