package net.sf.jclec.syntaxtree;

import net.sf.jclec.IFitness;
import net.sf.jclec.IIndividual;

import net.sf.jclec.base.AbstractIndividual;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * Individual that contains one syntax tree as genotype.
 * 
 * @author Sebastian Ventura
 */

@SuppressWarnings("deprecation")
public class SyntaxTreeIndividual extends AbstractIndividual<SyntaxTree> 
{
	/////////////////////////////////////////////////////////////////
	// --------------------------------------- Serialization constant
	/////////////////////////////////////////////////////////////////

	/** Generated by Eclipse */
	
	private static final long serialVersionUID = -2339079985634157433L;

	/////////////////////////////////////////////////////////////////
	// ------------------------------------------------- Constructors
	/////////////////////////////////////////////////////////////////

	/**
	 * Empty constructor.
	 */
	
	public SyntaxTreeIndividual() 
	{
		super();
	}

	/**
	 * Constructor that sets individual genotype.
	 * 
	 * @param genotype Individual genotype
	 */
	
	public SyntaxTreeIndividual(SyntaxTree genotype) 
	{
		super(genotype);
	}

	/**
	 * Constructor that sets individual genotype and fitness
	 * 
	 * @param genotype Individual genotype
	 * @param fitness  Individual fitness
	 */
	
	public SyntaxTreeIndividual(SyntaxTree genotype, IFitness fitness) 
	{
		super(genotype, fitness);
	}

	/////////////////////////////////////////////////////////////////
	// --------------------------- Implementing IIndividual interface
	/////////////////////////////////////////////////////////////////

	/**
	 * {@inheritDoc}
	 */

	public double distance(IIndividual other) 
	{
		// TODO Implement a syntax tree distance
		return 0;
	}

	/**
	 * {@inheritDoc}
	 */
	
	public IIndividual copy() 
	{
		if(fitness == null)
			return new SyntaxTreeIndividual(genotype.copy());
		else
			return new SyntaxTreeIndividual(genotype.copy(), fitness.copy());
	}
	
	/////////////////////////////////////////////////////////////////
	// ------------------------- Overwriting java.lang.Object methods
	/////////////////////////////////////////////////////////////////
	
	/**
	 * {@inheritDoc}
	 */
	
	@Override
	public boolean equals(Object other) 
	{
		if (other instanceof SyntaxTreeIndividual) {
			SyntaxTreeIndividual cother = (SyntaxTreeIndividual) other;
			EqualsBuilder eb = new EqualsBuilder();
			eb.append(genotype, cother.genotype);
			return eb.isEquals();
		}
		else {
			return false;
		}
	}
	
	/**
	 * {@inheritDoc}
	 */
	
	@Override
	public String toString()
	{
		ToStringBuilder tsb = new ToStringBuilder(this);
		tsb.append("genotype", genotype);
		tsb.append("fitness", fitness);
		return tsb.toString();
	}
}
