package net.sf.jclec.exprtree;

import org.apache.commons.configuration.Configuration;
import org.apache.commons.configuration.ConfigurationRuntimeException;

import net.sf.jclec.IConfigure;
import net.sf.jclec.ISpecies;

import net.sf.jclec.base.AbstractMutator;

/**
 * Mutator for ExprTreeIndividual (and its subclasses).
 * 
 * @author Sebastian Ventura
 */

public class ExprTreeMutator extends AbstractMutator implements IConfigure
{
	/////////////////////////////////////////////////////////////////
	// --------------------------------------- Serialization constant
	/////////////////////////////////////////////////////////////////
	
	/** Generated by Eclipse */

	private static final long serialVersionUID = 1953891763454588982L;

	/////////////////////////////////////////////////////////////////
	// --------------------------------------------------- Properties
	/////////////////////////////////////////////////////////////////

	/** Base operation for this expression tree mutator */
	
	protected IMutateExprTree baseOp;
	
	/////////////////////////////////////////////////////////////////
	// ------------------------------------------- Internal variables
	/////////////////////////////////////////////////////////////////

	/** Individual species */
	
	protected transient ExprTreeSpecies species;
	
	/** Individuals schema */
	
	protected transient ExprTreeSchema schema;
	
	/////////////////////////////////////////////////////////////////
	// ------------------------------------------------- Constructors
	/////////////////////////////////////////////////////////////////

	public ExprTreeMutator() 
	{
		super();
	}

	/////////////////////////////////////////////////////////////////
	// ----------------------------------------------- Public methods
	/////////////////////////////////////////////////////////////////

	// Setters and getters

	public IMutateExprTree getBaseOp() 
	{
		return baseOp;
	}

	public void setBaseOp(IMutateExprTree baseOp) 
	{
		this.baseOp = baseOp;
	}

	// IConfigure interface
	
	@Override
	@SuppressWarnings("unchecked")
	public void configure(Configuration settings) 
	{
		// Set base mutator name
		try {
			// Base mutator classname
			String baseOpClassname = 
				settings.getString("base-op[@type]");
			// Evaluator class
			Class<? extends IMutateExprTree> baseOpClass = 
				(Class<? extends IMutateExprTree>) Class.forName(baseOpClassname);
			// Evaluator instance
			IMutateExprTree baseOp = baseOpClass.newInstance();
			// Configure species
			if (baseOp instanceof IConfigure) {
				((IConfigure) baseOp).configure(settings.subset("base-op"));
			}
			// Set species
			setBaseOp(baseOp);
		} 
		catch (ClassNotFoundException e) {
			throw new ConfigurationRuntimeException("Illegal operator classname");
		} 
		catch (InstantiationException e) {
			throw new ConfigurationRuntimeException("Problems creating an instance of operator", e);
		} 
		catch (IllegalAccessException e) {
			throw new ConfigurationRuntimeException("Problems creating an instance of operator", e);
		}
	}

	// AbstractMutator methods

	@Override
	protected void prepareMutation() 
	{
		ISpecies spc = context.getSpecies();
		if (spc instanceof ExprTreeSpecies) {
			// Type conversion
			this.species = (ExprTreeSpecies) spc;
			// Sets genotype schema
			this.schema = ((ExprTreeSpecies) spc).getGenotypeSchema();
		}
		else {
			throw new IllegalStateException("Illegal species in context");
		}
	}

	@Override
	protected void mutateNext() 
	{
		// Actual individual
		ExprTree pgenotype = 
			((ExprTreeIndividual) parentsBuffer.get(parentsCounter)).getGenotype();
		// Mutate target, copy rest of trees
		ExprTree sonGenotype = this.baseOp.mutateExprTree(pgenotype, schema, randgen);
		// Add new individual to buffer
		sonsBuffer.add(species.createIndividual(sonGenotype));
	}
}
