package net.sf.jclec.exprtree.fun;

import net.sf.jclec.exprtree.fun.AbstractPrimitive;
import net.sf.jclec.exprtree.fun.ExprTreeFunction;

public class Sin extends AbstractPrimitive 
{
	/** Generated by Eclipse  */
	
	private static final long serialVersionUID = -2608609126532314560L;

	/**
	 * This operator receives two double arrays as arguments and return
	 * a double array as result.
	 */
	
	public Sin() 
	{
		super(new Class<?> [] {Double.class}, Double.class);
	}

	@Override
	protected void evaluate(ExprTreeFunction context) 
	{
		// Get arguments (in context stack)
		Double arg1 = pop(context);
		// Push result in context stack
		push(context, Math.sin(arg1));
	}

	// java.lang.Object methods
	
	public boolean equals(Object other)
	{
		return other instanceof Sin;
	}	
	
	public String toString()
	{
		return "+";
	}	
}
