package net.sf.jclec.intarray.mut;

import net.sf.jclec.intarray.IntArrayIndividual;
import net.sf.jclec.intarray.IntArrayMutator;

/**
 * One locus mutation in IntArrayIndividuals
 * 
 * @author Sebastian Ventura
 */

public class OneLocusMutator extends IntArrayMutator
{
	/////////////////////////////////////////////////////////////////
	// --------------------------------------------------- Parameters
	/////////////////////////////////////////////////////////////////
	
	/** Generated by Eclipse */
	
	private static final long serialVersionUID = 4051327838076744754L;

	/////////////////////////////////////////////////////////////////
	// ------------------------------------------------- Constructors
	/////////////////////////////////////////////////////////////////
	
	/**
	 * Empty constructor
	 */
	
	public OneLocusMutator() 
	{
		super();
	}

	/////////////////////////////////////////////////////////////////
	// ----------------------------------------------- Public methods
	/////////////////////////////////////////////////////////////////

	// AbstractMutator methods

	/**
	 * {@inheritDoc}
	 */
	
	@Override
	protected void mutateNext() 
	{
		// Genome length
		int gl = species.getGenotypeLength();
		// Individual to mutate
		IntArrayIndividual mutant = 
			(IntArrayIndividual) parentsBuffer.get(parentsCounter);
		// Creates mutant genotype
		int [] mgenome = new int[gl];
		System.arraycopy(mutant.getGenotype(), 0, mgenome, 0, gl);
		// Choose mutation point
		int mp = getMutableLocus();
		// Flip selected point
		flip(mgenome, mp);
		// Returns mutant
		sonsBuffer.add(species.createIndividual(mgenome));
	}

	// java.lang.Object methods

	public boolean equals(Object other)
	{
		if (other instanceof OneLocusMutator) {
			return true;
		}
		else {
			return false;
		}
	}	
}
